import { db, error, json, requireAuth } from '@appdeploy/sdk';
import { getOrgAccess } from './org';

type PrimaryRole='employer'|'talent';
type RoleRecord={role:PrimaryRole;status:'active';source:'claimed'|'legacy';createdAt:string;updatedAt:string};
type EmployerProfile={companyName:string;website:string;country:string;teamSize:string;hiringFocus:string;updatedAt:string};
type PublicRoleLead={company:string;email:string;role:string;hires:number;notes:string;createdAt:string};
type PublicTalentLead={name:string;email:string;role:string;experience:string;availability:string;linkedin:string;createdAt:string};
type ClientRole={role:string;hires:number;seniority:string;notes:string;status:string;createdAt:string;sourceLeadId?:string};
type InitialTalentProfile={name:string;email:string;role:string;years:number;city:string;availability:string;linkedin:string;qualification:string;systems:string;internet:string;backup:string;summary:string;completion:number;updatedAt:string;discoverable:boolean;previewId:string};
const table=(name:string,id:string)=>`${name}:${id}`;
const now=()=>new Date().toISOString();
const clean=(v:unknown,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
const first=async<T>(name:string)=>{const {items}=await db.list<T>(name,{limit:1});return items[0]||null};
const yearsFrom=(v:string)=>Math.max(0,Math.min(60,Number(v.match(/\d+/)?.[0]||0)));
async function importEmployerHistory(userId:string,email:string){if(!email)return;const[publicLeads,own]=await Promise.all([db.list<PublicRoleLead>('public-role-leads',{limit:100}),db.list<ClientRole>(table('client-role-requests',userId),{limit:100})]),seen=new Set(own.items.map(x=>x.sourceLeadId).filter(Boolean)),matches=publicLeads.items.filter(x=>x.email.toLowerCase()===email.toLowerCase()&&!seen.has(x.id));if(matches.length)await db.add(table('client-role-requests',userId),matches.map(x=>({role:x.role,hires:x.hires,seniority:'To confirm',notes:x.notes,status:'calibration',createdAt:x.createdAt,sourceLeadId:x.id})))}
async function importTalentHistory(userId:string,email:string){if(!email||await first<InitialTalentProfile>(table('talent-profile',userId)))return;const{items}=await db.list<PublicTalentLead>('talent-applications',{limit:100}),x=[...items].filter(i=>i.email.toLowerCase()===email.toLowerCase()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];if(!x)return;const fields=[x.name,x.email,x.role,'',x.availability,'','','','', ''],completion=Math.round(fields.filter(Boolean).length/fields.length*100);await db.add(table('talent-profile',userId),[{name:x.name,email:x.email,role:x.role,years:yearsFrom(x.experience),city:'',availability:x.availability,linkedin:x.linkedin,qualification:'',systems:'',internet:'',backup:'',summary:'',completion,updatedAt:now(),discoverable:false,previewId:''}])}
export async function getPrimaryAccountRole(userId:string):Promise<(RoleRecord&{id?:string})|null>{const saved=await first<RoleRecord>(table('account-role',userId));if(saved)return saved;const[talent,{items:clientRoles},{items:clientShortlists}]=await Promise.all([first<Record<string,unknown>>(table('talent-profile',userId)),db.list<Record<string,unknown>>(table('client-role-requests',userId),{limit:1}),db.list<Record<string,unknown>>(table('client-shortlists',userId),{limit:1})]);const employer=clientRoles.length>0||clientShortlists.length>0;if(talent&&!employer)return{role:'talent',status:'active',source:'legacy',createdAt:'',updatedAt:''};if(employer&&!talent)return{role:'employer',status:'active',source:'legacy',createdAt:'',updatedAt:''};return null}
export function requiredAccountRoleForPath(path:string):PrimaryRole|null{const p=path.toLowerCase();if(p.startsWith('/api/client/')||p.startsWith('/api/employer/'))return'employer';if(p.startsWith('/api/talent/')&&p!=='/api/talent/apply')return'talent';return null}
async function employerProfile(userId:string){return first<EmployerProfile>(table('employer-profile',userId))}
export const accessRoutes={
 'GET /api/access/me':[requireAuth(),async ctx=>{const[accountRole,agencyAccess]=await Promise.all([getPrimaryAccountRole(ctx.user!.userId),getOrgAccess(ctx.user!)]),agencyEnabled=agencyAccess.status==='active'&&agencyAccess.role!=='None',availableWorkspaces:string[]=[];if(accountRole?.role==='employer')availableWorkspaces.push('employer');if(accountRole?.role==='talent')availableWorkspaces.push('talent');if(agencyEnabled)availableWorkspaces.push('agency');return json({accountRole,agencyAccess:agencyEnabled?agencyAccess:null,employerProfile:accountRole?.role==='employer'?await employerProfile(ctx.user!.userId):null,availableWorkspaces,needsRoleChoice:!accountRole&&availableWorkspaces.length===0})}],
 'POST /api/access/claim':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as{role?:string;companyName?:string},role=clean(b.role,20) as PrimaryRole;if(!['employer','talent'].includes(role))return error('Choose Employer or Talent.',400);const companyName=role==='employer'?clean(b.companyName,160):'';if(role==='employer'&&!companyName)return error('Company name is required for an employer account.',400);const existing=await getPrimaryAccountRole(ctx.user!.userId);if(existing&&existing.role!==role)return error(`This account is already registered as ${existing.role}. Workspace roles cannot be self-switched.`,409);const stamp=now(),record:RoleRecord={role,status:'active',source:'claimed',createdAt:existing?.createdAt||stamp,updatedAt:stamp},t=table('account-role',ctx.user!.userId),saved=await first<RoleRecord>(t);let id=saved?.id;if(id)await db.update(t,[{id,record}]);else[id]=await db.add(t,[record]);if(!id)return error('Unable to register workspace role.',500);if(role==='employer'){const pt=table('employer-profile',ctx.user!.userId),p=await first<EmployerProfile>(pt),profile:EmployerProfile={companyName,website:p?.website||'',country:p?.country||'United Kingdom',teamSize:p?.teamSize||'',hiringFocus:p?.hiringFocus||'Accounting & finance',updatedAt:stamp};if(p?.id)await db.update(pt,[{id:p.id,record:profile}]);else await db.add(pt,[profile]);await importEmployerHistory(ctx.user!.userId,ctx.user!.email||'')}else await importTalentHistory(ctx.user!.userId,ctx.user!.email||'');return json({role,status:'active',locked:true})}],
 'GET /api/employer/profile':[requireAuth(),async ctx=>{const role=await getPrimaryAccountRole(ctx.user!.userId);if(role?.role!=='employer')return error('Employer workspace access required.',403);return json({item:await employerProfile(ctx.user!.userId)})}],
 'PUT /api/employer/profile':[requireAuth(),async ctx=>{const role=await getPrimaryAccountRole(ctx.user!.userId);if(role?.role!=='employer')return error('Employer workspace access required.',403);const b=(ctx.body||{}) as Partial<EmployerProfile>,companyName=clean(b.companyName,160);if(!companyName)return error('Company name is required.',400);const record:EmployerProfile={companyName,website:clean(b.website,240),country:clean(b.country,100)||'United Kingdom',teamSize:clean(b.teamSize,80),hiringFocus:clean(b.hiringFocus,300)||'Accounting & finance',updatedAt:now()},t=table('employer-profile',ctx.user!.userId),existing=await first<EmployerProfile>(t);let id=existing?.id;if(id)await db.update(t,[{id,record}]);else[id]=await db.add(t,[record]);return id?json({item:{id,...record}}):error('Unable to save company profile.',500)}],
};
