import { db, error, json, requireAuth, secrets } from '@appdeploy/sdk';
import { appendAudit, getOrgAccess, hasOrgPermission } from './org';

type Opportunity={company:string;clientLabel:string;roleTitle:string;location:string;summary:string;requirements:string;requiredSkills:string[];systems:string[];minYears:number;salaryText:string;workMode:string;vacancyCount:number;urgency:string;opportunityScore:number;sourceType:string;sourceUrl:string;sourceTitle:string;sourceExternalId?:string;status:string;accountId:string;roleId:string;publicationId:string;createdAt:string;updatedAt:string;evidenceDate?:string};
type AdzunaJob={id?:string;title?:string;description?:string;redirect_url?:string;created?:string;salary_min?:number;salary_max?:number;company?:{display_name?:string};location?:{display_name?:string;area?:string[]};category?:{label?:string;tag?:string};contract_time?:string;contract_type?:string};
type AdzunaSearch={count?:number;results?:AdzunaJob[]};
type SyncRecord={status:string;fetched:number;imported:number;duplicates:number;skipped:number;queries:string[];createdAt:string};
const table=(n:string,id:string)=>`${n}:${id}`;const clean=(v:unknown,max=1000)=>typeof v==='string'?v.replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim().slice(0,max):'';const now=()=>new Date().toISOString();
const financeTerms=['accountant','accounting','bookkeeper','bookkeeping','payroll','accounts assistant','accounts payable','accounts receivable','financial analyst','management accountant','finance','audit','auditor','ledger','credit control','tax'];const financeRelevant=(v:string)=>financeTerms.some(x=>v.toLowerCase().includes(x));
const systems=(v:string)=>[['Xero',/\bxero\b/i],['Sage',/\bsage\b/i],['QuickBooks',/quickbooks/i],['Excel',/\bexcel\b/i],['FreeAgent',/freeagent/i],['IRIS',/\biris\b/i],['TaxCalc',/taxcalc/i],['Power BI',/power\s*bi/i]].filter(([,r])=>(r as RegExp).test(v)).map(([n])=>n as string);
const skills=(v:string)=>[['Bookkeeping',/bookkeep/i],['Payroll',/payroll/i],['VAT',/\bvat\b/i],['Management accounts',/management accounts/i],['Year-end accounts',/year[- ]end accounts/i],['Accounts payable',/accounts payable|\bap\b/i],['Accounts receivable',/accounts receivable|\bar\b/i],['Tax',/\btax\b|corporation tax|self assessment/i],['Audit',/\baudit/i],['Reconciliations',/reconcil/i],['Client communication',/client communication|client-facing|client portfolio/i]].filter(([,r])=>(r as RegExp).test(v)).map(([n])=>n as string).slice(0,10);
const years=(v:string)=>Math.max(0,Math.min(30,Number(v.match(/(\d+)\+?\s*(?:years?|yrs?)/i)?.[1]||0)));const workMode=(v:string)=>/fully remote|\bremote\b/i.test(v)?'Remote':/hybrid/i.test(v)?'Hybrid':'Not specified';const salary=(j:AdzunaJob)=>{const a=Number(j.salary_min)||0,b=Number(j.salary_max)||0;if(a&&b)return `£${Math.round(a).toLocaleString('en-GB')}–£${Math.round(b).toLocaleString('en-GB')}`;if(a)return `From £${Math.round(a).toLocaleString('en-GB')}`;if(b)return `Up to £${Math.round(b).toLocaleString('en-GB')}`;return''};
function score(x:{title:string;description:string;location:string;systems:string[];skills:string[];minYears:number;salaryText:string;mode:string;urgency:string}){let s=0;if(financeRelevant(`${x.title} ${x.description}`))s+=40;if(/uk|united kingdom|england|london|scotland|wales|northern ireland/i.test(x.location))s+=10;if(/remote|hybrid/i.test(x.mode))s+=10;if(x.skills.length)s+=10;if(x.systems.length)s+=10;if(x.minYears>0)s+=5;if(x.salaryText)s+=5;if(x.urgency==='high')s+=10;return Math.min(100,s)}
async function allow(user:{userId:string;email?:string;name?:string},permission:string){const a=await getOrgAccess(user);return hasOrgPermission(a,permission)?a:null}
async function credentials(){const names=await secrets.listSecretNames(),configured=names.includes('ADZUNA_APP_ID')&&names.includes('ADZUNA_APP_KEY');if(!configured)return null;const[appId,appKey]=await Promise.all([secrets.readSecret('ADZUNA_APP_ID'),secrets.readSecret('ADZUNA_APP_KEY')]);return{appId,appKey}}
async function search(appId:string,appKey:string,what:string,resultsPerPage:number){const q=new URLSearchParams({app_id:appId,app_key:appKey,results_per_page:String(resultsPerPage),what,sort_by:'date','content-type':'application/json'}),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(`https://api.adzuna.com/v1/api/jobs/gb/search/1?${q.toString()}`,{headers:{Accept:'application/json'},signal:controller.signal});if(!r.ok){const e=new Error(`Adzuna request failed with HTTP ${r.status}`) as Error&{status?:number};e.status=r.status;throw e}return await r.json() as AdzunaSearch}finally{clearTimeout(timer)}}
function normalise(j:AdzunaJob,stamp:string):Opportunity|null{const title=clean(j.title,180),description=clean(j.description,2200);if(!title||!financeRelevant(`${title} ${description}`))return null;const company=clean(j.company?.display_name,160)||'Employer to verify',location=clean(j.location?.display_name,180)||clean(j.location?.area?.join(', '),180)||'United Kingdom',combined=`${title} ${description}`,sys=systems(combined),req=skills(combined),minYears=years(combined),salaryText=salary(j),mode=workMode(combined),created=j.created?new Date(j.created):null,urgency=created&&Number.isFinite(created.getTime())&&Date.now()-created.getTime()<=10*86400000?'high':'normal',externalId=clean(j.id,160),sourceUrl=clean(j.redirect_url,1000);if(!externalId&&!sourceUrl)return null;return{company,clientLabel:'UK employer',roleTitle:title,location,summary:description.slice(0,900),requirements:description,requiredSkills:req,systems:sys,minYears,salaryText,workMode:mode,vacancyCount:1,urgency,opportunityScore:score({title,description,location,systems:sys,skills:req,minYears,salaryText,mode,urgency}),sourceType:'adzuna_api',sourceUrl,sourceTitle:`Adzuna · ${company}`,sourceExternalId:externalId,status:'signal',accountId:'',roleId:'',publicationId:'',createdAt:stamp,updatedAt:stamp,evidenceDate:j.created||stamp.slice(0,10)}}
export const adzunaRoutes={
 'GET /api/radar/adzuna/status':[requireAuth(),async ctx=>{const a=await allow(ctx.user!,'read');if(!a)return error('Organisation access is unavailable.',403);const names=await secrets.listSecretNames(),configured=names.includes('ADZUNA_APP_ID')&&names.includes('ADZUNA_APP_KEY'),{items}=await db.list<SyncRecord>(table('agency-adzuna-sync',a.ownerId),{limit:10}),last=[...items].sort((x,y)=>y.createdAt.localeCompare(x.createdAt))[0]||null;return json({configured,connected:configured&&last?.status==='ok',state:!configured?'credential_required':last?.status==='ok'?'connected':'configured',country:'gb',category:'Accounting & Finance',lastSync:last})}],
 'POST /api/radar/adzuna/sync':[requireAuth(),async ctx=>{const a=await allow(ctx.user!,'crm');if(!a)return error('Your role cannot sync Adzuna hiring signals.',403);const c=await credentials();if(!c)return error('Adzuna credentials are not configured. Add ADZUNA_APP_ID and ADZUNA_APP_KEY first.',409);const b=(ctx.body||{}) as{queries?:unknown;resultsPerPage?:unknown},defaults=['accountant','bookkeeper','payroll','management accountant','accounts assistant','financial analyst'],queries=Array.isArray(b.queries)?[...new Set(b.queries.map(x=>clean(x,80)).filter(Boolean))].slice(0,6):defaults,resultsPerPage=Math.max(5,Math.min(20,Number(b.resultsPerPage)||10));try{const batches=await Promise.all(queries.map(q=>search(c.appId,c.appKey,q,resultsPerPage))),jobs=batches.flatMap(x=>Array.isArray(x.results)?x.results:[]),ot=table('agency-opportunities',a.ownerId),{items:existing}=await db.list<Opportunity>(ot,{limit:180}),seenIds=new Set(existing.filter(x=>x.sourceType==='adzuna_api').map(x=>x.sourceExternalId||'').filter(Boolean)),seenUrls=new Set(existing.filter(x=>x.sourceType==='adzuna_api').map(x=>x.sourceUrl).filter(Boolean)),stamp=now(),records:Opportunity[]=[],batchSeen=new Set<string>();let duplicates=0,skipped=0;for(const job of jobs){const record=normalise(job,stamp);if(!record){skipped++;continue}const key=record.sourceExternalId||record.sourceUrl;if(batchSeen.has(key)||record.sourceExternalId&&seenIds.has(record.sourceExternalId)||record.sourceUrl&&seenUrls.has(record.sourceUrl)){duplicates++;continue}batchSeen.add(key);records.push(record)}if(records.length)await db.add(ot,records.slice(0,60));const sync:SyncRecord={status:'ok',fetched:jobs.length,imported:Math.min(records.length,60),duplicates,skipped,queries,createdAt:stamp};await db.add(table('agency-adzuna-sync',a.ownerId),[sync]);await appendAudit(a.ownerId,ctx.user!,'radar.adzuna.synced','source','adzuna',`${sync.imported} imported:${sync.fetched} fetched`);return json(sync)}catch(e){const status=(e as{status?:number}).status||0;if(status===401||status===403)return error('Adzuna rejected the configured credentials. Re-enter the app ID and app key.',502);if(status===429)return error('Adzuna rate limit reached. Wait before syncing again.',429);return error('Adzuna could not be reached. The existing Radar data is unchanged.',502)}}],
};
