import { randomUUID } from 'node:crypto';
import { milestone3Routes } from './milestone3';
import { milestone4Routes } from './milestone4';
import { milestone5Routes } from './milestone5';
import { milestone6Routes } from './milestone6';
import { accessRoutes, getPrimaryAccountRole, requiredAccountRoleForPath } from './access';
import { getOrgAccess, hasOrgPermission, orgOwnerId, permissionForPath } from './org';
import { intakeRoutes, mirrorRoleLead, mirrorTalentLead } from './intake';
import { adzunaRoutes } from './adzuna';
import { router, json, error, requireAuth, db, storage, auth } from '@appdeploy/sdk';

type LeadBody={company?:string;email?:string;role?:string;hires?:number;notes?:string};
type TalentApplyBody={name?:string;email?:string;role?:string;experience?:string;availability?:string;linkedin?:string};
type ClientRoleBody={role?:string;hires?:number;seniority?:string;notes?:string};
type ClientRole={role:string;hires:number;seniority:string;notes:string;status:string;createdAt:string};
type TalentProfile={name:string;email:string;role:string;years:number;city:string;availability:string;linkedin:string;qualification:string;systems:string;internet:string;backup:string;summary:string;completion:number;updatedAt:string;cvPath?:string;cvName?:string;discoverable?:boolean;previewId?:string};type PublicTalentPreview={talentUserId:string;role:string;years:number;city:string;availability:string;qualification:string;systems:string;summary:string;remoteReady:boolean;updatedAt:string};
type AgencyCandidate={name:string;email:string;role:string;years:number;city:string;availability:string;skills:string;summary:string;stage:string;technical:number;communication:number;experienceFit:number;remoteReadiness:number;references:number;score:number;createdAt:string};
type AgencyRole={clientName:string;role:string;seniority:string;hires:number;model:string;status:string;notes:string;createdAt:string};
type Placement={candidateName:string;clientName:string;role:string;model:string;feeGBP:number;fxRate:number;feeZAR:number;status:string;createdAt:string};
type ManagedSeat={talentName:string;clientName:string;role:string;chargeGBP:number;talentCostZAR:number;fxRate:number;monthlyRevenueZAR:number;grossContributionZAR:number;marginPct:number;status:string;createdAt:string};
type SharedCandidate={sourceId:string;name:string;role:string;years:number;city:string;availability:string;skills:string;summary:string;score:number;decision:string;interviewAt:string};
type SharedShortlist={code:string;ownerId:string;roleId:string;clientName:string;role:string;candidates:SharedCandidate[];createdAt:string};

const clean=(v:unknown,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
const validEmail=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const num=(v:unknown,min=0,max=1e9)=>Math.max(min,Math.min(max,Number(v)||0));
const s=(v:unknown)=>Math.round(num(v,0,100));
const score=(b:{technical?:unknown;communication?:unknown;experienceFit?:unknown;remoteReadiness?:unknown;references?:unknown})=>Math.round(s(b.technical)*.3+s(b.communication)*.2+s(b.experienceFit)*.2+s(b.remoteReadiness)*.15+s(b.references)*.15);
const table=(name:string,userId:string)=>`${name}:${userId}`;
const first=async<T>(name:string)=>{const {items}=await db.list<T>(name,{limit:1});return items[0]||null};

const routed=router({
 'GET /api/_healthcheck':[async()=>json({message:'Success'})],
 'POST /api/leads/role-request':[async ctx=>{const b=(ctx.body||{}) as LeadBody;const company=clean(b.company,120),email=clean(b.email,160),role=clean(b.role,100);if(!company||!validEmail(email)||!role)return error('Company, valid work email and role are required.',400);const user=await auth.getUser(ctx.event),hires=num(b.hires,1,50)||1,notes=clean(b.notes,1500),createdAt=new Date().toISOString(),[id]=await db.add('public-role-leads',[{company,email,role,hires,notes,ownerId:user?.userId||null,status:'new',createdAt}]);if(!id)return error('Unable to save role request.',500);await mirrorRoleLead(id,{company,email,role,hires,notes,createdAt});if(user&&(await getPrimaryAccountRole(user.userId))?.role==='employer'){const ownTable=table('client-role-requests',user.userId),{items}=await db.list<ClientRole>(ownTable,{limit:50});if(!items.some(x=>x.role.toLowerCase()===role.toLowerCase()&&x.status!=='closed'))await db.add(ownTable,[{role,hires,seniority:'To confirm',notes,status:'calibration',createdAt}])}return json({id,status:'received'},201)}],
 'POST /api/talent/apply':[async ctx=>{const b=(ctx.body||{}) as TalentApplyBody;const name=clean(b.name,120),email=clean(b.email,160),role=clean(b.role,100);if(!name||!validEmail(email)||!role)return error('Name, valid email and primary role are required.',400);const experience=clean(b.experience,30),availability=clean(b.availability,50),linkedin=clean(b.linkedin,300),createdAt=new Date().toISOString(),[id]=await db.add('talent-applications',[{name,email,role,experience,availability,linkedin,stage:'applied',source:'website',createdAt}]);if(!id)return error('Unable to save talent profile.',500);await mirrorTalentLead(id,{name,email,role,experience,availability,linkedin,createdAt});return json({id,stage:'applied'},201)}],
 'GET /api/public/talent-previews':[async()=>{const{items}=await db.list<PublicTalentPreview>('public-talent-previews',{limit:60});const safe=items.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(x=>({id:x.id,role:x.role,years:x.years,city:x.city,availability:x.availability,qualification:x.qualification,systems:x.systems,summary:x.summary,remoteReady:x.remoteReady,updatedAt:x.updatedAt}));return json({items:safe})}],
 'GET /api/me':[requireAuth(),async ctx=>json({user:ctx.user})],

 'GET /api/client/role-requests':[requireAuth(),async ctx=>{const {items}=await db.list<ClientRole>(table('client-role-requests',ctx.user!.userId),{limit:50});return json({items:items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))})}],
 'POST /api/client/role-requests':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as ClientRoleBody;const role=clean(b.role,100);if(!role)return error('Role is required.',400);const record:ClientRole={role,hires:num(b.hires,1,50)||1,seniority:clean(b.seniority,50)||'Mid-level',notes:clean(b.notes,2000),status:'calibration',createdAt:new Date().toISOString()};const [id]=await db.add(table('client-role-requests',ctx.user!.userId),[record]);return id?json({id,...record},201):error('Unable to create role request.',500)}],
 'GET /api/client/shortlists':[requireAuth(),async ctx=>{const {items}=await db.list<SharedShortlist>(table('client-shortlists',ctx.user!.userId),{limit:30});return json({items:items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))})}],
 'POST /api/client/redeem-shortlist':[requireAuth(),async ctx=>{const code=clean((ctx.body as {code?:string}||{}).code,64).replace(/[^A-Za-z0-9]/g,'').toUpperCase();if(code.length<12)return error('Enter a valid shortlist code.',400);const shared=await first<SharedShortlist>(`shortlist-share:${code}`);if(!shared)return error('Shortlist code not found.',404);const ownTable=table('client-shortlists',ctx.user!.userId);const {items}=await db.list<SharedShortlist>(ownTable,{limit:30,filter:{code}});if(items.length)return json({item:items[0],alreadyRedeemed:true});const copy={...shared,candidates:shared.candidates.map(c=>({...c,decision:'reviewing',interviewAt:''}))};const [id]=await db.add(ownTable,[copy]);return id?json({item:{id,...copy}},201):error('Unable to add shortlist.',500)}],
 'PUT /api/client/shortlists/:id':[requireAuth(),async ctx=>{const ownTable=table('client-shortlists',ctx.user!.userId);const [existing]=await db.get<SharedShortlist>(ownTable,[ctx.params.id]);if(!existing)return error('Shortlist not found.',404);const b=(ctx.body||{}) as {candidateId?:string;decision?:string;interviewAt?:string};const candidateId=clean(b.candidateId,100),decision=clean(b.decision,30);if(!candidateId||!['reviewing','interview','declined'].includes(decision))return error('Candidate and valid decision are required.',400);const candidates=existing.candidates.map(c=>c.sourceId===candidateId?{...c,decision,interviewAt:decision==='interview'?clean(b.interviewAt,80):''}:c);const [ok]=await db.update(ownTable,[{id:ctx.params.id,record:{...existing,candidates}}]);if(!ok)return error('Unable to update shortlist.',500);const responseTable=`shortlist-response:${existing.code}`;const response={clientUserId:ctx.user!.userId,code:existing.code,candidates:candidates.map(c=>({sourceId:c.sourceId,decision:c.decision,interviewAt:c.interviewAt})),updatedAt:new Date().toISOString()};const current=await first<typeof response>(responseTable);if(current)await db.update(responseTable,[{id:current.id,record:response}]);else await db.add(responseTable,[response]);return json({ok:true,candidates})}],

 'GET /api/talent/profile':[requireAuth(),async ctx=>{const item=await first<TalentProfile>(table('talent-profile',ctx.user!.userId));return json({item})}],
 'PUT /api/talent/profile':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<TalentProfile>;const name=clean(b.name,120),email=clean(b.email,160),role=clean(b.role,100);if(!name||!validEmail(email)||!role)return error('Name, valid email and primary role are required.',400);const city=clean(b.city,100),availability=clean(b.availability,60),qualification=clean(b.qualification,160),systems=clean(b.systems,500),internet=clean(b.internet,120),backup=clean(b.backup,120),summary=clean(b.summary,1200),fields=[name,email,role,city,availability,qualification,systems,internet,backup,summary],completion=Math.round(fields.filter(Boolean).length/fields.length*100),ownTable=table('talent-profile',ctx.user!.userId),existing=await first<TalentProfile>(ownTable),discoverable=Boolean(b.discoverable),stamp=new Date().toISOString();let previewId=existing?.previewId||'';const preview:PublicTalentPreview={talentUserId:ctx.user!.userId,role,years:num(b.years,0,60),city,availability,qualification,systems,summary,remoteReady:Boolean(internet&&backup),updatedAt:stamp};if(discoverable){if(previewId){const[current]=await db.get<PublicTalentPreview>('public-talent-previews',[previewId]);if(current){const[ok]=await db.update('public-talent-previews',[{id:previewId,record:preview}]);if(!ok)return error('Unable to update employer preview.',500)}else previewId=''}if(!previewId){[previewId]=await db.add('public-talent-previews',[preview]);if(!previewId)return error('Unable to publish employer preview.',500)}}else if(previewId){await db.delete('public-talent-previews',[previewId]);previewId=''}const record:TalentProfile={...(existing||{} as TalentProfile),name,email,role,years:num(b.years,0,60),city,availability,linkedin:clean(b.linkedin,300),qualification,systems,internet,backup,summary,completion,discoverable,previewId,updatedAt:stamp};if(existing){await db.update(ownTable,[{id:existing.id,record}]);return json({item:{id:existing.id,...record}})}const[id]=await db.add(ownTable,[record]);return id?json({item:{id,...record}},201):error('Unable to save profile.',500)}],
 'POST /api/talent/cv':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as {name?:string;type?:string;base64?:string};const name=clean(b.name,180),type=clean(b.type,100),base64=typeof b.base64==='string'?b.base64:'';const allowed=['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'];if(!name||!allowed.includes(type)||!base64)return error('Upload a PDF, DOC or DOCX CV.',400);if(base64.length>820000)return error('CV must be smaller than about 600 KB for this preview upload.',413);const ext=name.toLowerCase().endsWith('.pdf')?'pdf':name.toLowerCase().endsWith('.docx')?'docx':'doc';const path=`talent/${ctx.user!.userId}/cv.${ext}`;const [ok]=await storage.write([{path,content:base64,contentType:type}]);if(!ok)return error('Unable to store CV.',500);const ownTable=table('talent-profile',ctx.user!.userId);const existing=await first<TalentProfile>(ownTable);if(existing)await db.update(ownTable,[{id:existing.id,record:{...existing,cvPath:path,cvName:name,updatedAt:new Date().toISOString()}}]);return json({ok:true,name,path})}],
 'GET /api/talent/cv-url':[requireAuth(),async ctx=>{const existing=await first<TalentProfile>(table('talent-profile',ctx.user!.userId));if(!existing?.cvPath)return error('No CV uploaded.',404);const [item]=await storage.url([existing.cvPath]);return json({url:item.url,name:existing.cvName})}],

 'GET /api/agency/overview':[requireAuth(),async ctx=>{const uid=await orgOwnerId(ctx.user!);const [{items:candidates},{items:roles},{items:placements},{items:seats},{items:shortlists}]=await Promise.all([db.list<AgencyCandidate>(table('agency-candidates',uid),{limit:80}),db.list<AgencyRole>(table('agency-roles',uid),{limit:50}),db.list<Placement>(table('agency-placements',uid),{limit:50}),db.list<ManagedSeat>(table('agency-seats',uid),{limit:50}),db.list<{code:string;clientName:string;role:string;createdAt:string}>(table('agency-shortlists',uid),{limit:50})]);const mrr=seats.filter(x=>x.status==='active').reduce((a,x)=>a+x.monthlyRevenueZAR,0),gp=seats.filter(x=>x.status==='active').reduce((a,x)=>a+x.grossContributionZAR,0),placementRevenue=placements.reduce((a,x)=>a+x.feeZAR,0);return json({candidates,roles,placements,seats,shortlists,metrics:{candidateBench:candidates.length,qualified:candidates.filter(x=>x.stage==='qualified'||x.stage==='shortlisted').length,activeRoles:roles.filter(x=>x.status!=='closed').length,managedSeats:seats.filter(x=>x.status==='active').length,mrr,gp,placementRevenue}})}],
 'POST /api/agency/candidates':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<AgencyCandidate>;const name=clean(b.name,120),role=clean(b.role,100);if(!name||!role)return error('Candidate name and role are required.',400);const record:AgencyCandidate={name,email:clean(b.email,160),role,years:num(b.years,0,60),city:clean(b.city,100),availability:clean(b.availability,60),skills:clean(b.skills,700),summary:clean(b.summary,1200),stage:clean(b.stage,30)||'sourced',technical:s(b.technical),communication:s(b.communication),experienceFit:s(b.experienceFit),remoteReadiness:s(b.remoteReadiness),references:s(b.references),score:score(b),createdAt:new Date().toISOString()};const [id]=await db.add(table('agency-candidates',await orgOwnerId(ctx.user!)),[record]);return id?json({item:{id,...record}},201):error('Unable to add candidate.',500)}],
 'PUT /api/agency/candidates/:id':[requireAuth(),async ctx=>{const ownTable=table('agency-candidates',await orgOwnerId(ctx.user!));const [existing]=await db.get<AgencyCandidate>(ownTable,[ctx.params.id]);if(!existing)return error('Candidate not found.',404);const b=(ctx.body||{}) as Partial<AgencyCandidate>;const record={...existing,stage:clean(b.stage,30)||existing.stage,technical:b.technical===undefined?existing.technical:s(b.technical),communication:b.communication===undefined?existing.communication:s(b.communication),experienceFit:b.experienceFit===undefined?existing.experienceFit:s(b.experienceFit),remoteReadiness:b.remoteReadiness===undefined?existing.remoteReadiness:s(b.remoteReadiness),references:b.references===undefined?existing.references:s(b.references)};record.score=score(record);const [ok]=await db.update(ownTable,[{id:ctx.params.id,record}]);return ok?json({item:{id:ctx.params.id,...record}}):error('Unable to update candidate.',500)}],
 'POST /api/agency/roles':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<AgencyRole>;const clientName=clean(b.clientName,120),role=clean(b.role,100);if(!clientName||!role)return error('Client and role are required.',400);const record:AgencyRole={clientName,role,seniority:clean(b.seniority,50)||'Mid-level',hires:num(b.hires,1,50)||1,model:clean(b.model,40)||'Direct Hire',status:clean(b.status,30)||'active',notes:clean(b.notes,1600),createdAt:new Date().toISOString()};const [id]=await db.add(table('agency-roles',await orgOwnerId(ctx.user!)),[record]);return id?json({item:{id,...record}},201):error('Unable to create role.',500)}],
 'POST /api/agency/shortlists/share':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as {roleId?:string;candidateIds?:string[]};const roleId=clean(b.roleId,100),candidateIds=Array.isArray(b.candidateIds)?b.candidateIds.slice(0,8).map(x=>clean(x,100)).filter(Boolean):[];if(!roleId||candidateIds.length===0)return error('Select a role and at least one candidate.',400);const uid=await orgOwnerId(ctx.user!);const [role]=await db.get<AgencyRole>(table('agency-roles',uid),[roleId]);if(!role)return error('Role not found.',404);const found=await db.get<AgencyCandidate>(table('agency-candidates',uid),candidateIds);const candidates:SharedCandidate[]=found.filter((x):x is AgencyCandidate=>Boolean(x)).map((c,i)=>({sourceId:candidateIds[i]||'',name:c.name,role:c.role,years:c.years,city:c.city,availability:c.availability,skills:c.skills,summary:c.summary,score:c.score,decision:'reviewing',interviewAt:''}));if(!candidates.length)return error('No valid candidates selected.',400);const code=randomUUID().replace(/-/g,'').slice(0,20).toUpperCase();const shared:SharedShortlist={code,ownerId:uid,roleId,clientName:role.clientName,role:role.role,candidates,createdAt:new Date().toISOString()};const [shareId]=await db.add(`shortlist-share:${code}`,[shared]);if(!shareId)return error('Unable to create shortlist share.',500);await db.add(table('agency-shortlists',uid),[{code,clientName:role.clientName,role:role.role,candidateCount:candidates.length,createdAt:shared.createdAt}]);return json({code,shared},201)}],
 'GET /api/agency/shortlists/:code/responses':[requireAuth(),async ctx=>{const code=clean(ctx.params.code,64).replace(/[^A-Za-z0-9]/g,'').toUpperCase();const shared=await first<SharedShortlist>(`shortlist-share:${code}`);if(!shared||shared.ownerId!==(await orgOwnerId(ctx.user!)))return error('Shortlist not found.',404);const response=await first<{candidates:{sourceId:string;decision:string;interviewAt:string}[];updatedAt:string}>(`shortlist-response:${code}`);return json({response})}],
 'POST /api/agency/placements':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<Placement>;const candidateName=clean(b.candidateName,120),clientName=clean(b.clientName,120),role=clean(b.role,100);if(!candidateName||!clientName||!role)return error('Candidate, client and role are required.',400);const fxRate=num(b.fxRate,1,1000)||24,feeGBP=num(b.feeGBP,0,1e7);const record:Placement={candidateName,clientName,role,model:clean(b.model,50)||'Direct Hire',feeGBP,fxRate,feeZAR:Math.round(feeGBP*fxRate),status:clean(b.status,30)||'placed',createdAt:new Date().toISOString()};const [id]=await db.add(table('agency-placements',await orgOwnerId(ctx.user!)),[record]);return id?json({item:{id,...record}},201):error('Unable to save placement.',500)}],
 'POST /api/agency/seats':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<ManagedSeat>;const talentName=clean(b.talentName,120),clientName=clean(b.clientName,120),role=clean(b.role,100);if(!talentName||!clientName||!role)return error('Talent, client and role are required.',400);const fxRate=num(b.fxRate,1,1000)||24,chargeGBP=num(b.chargeGBP,0,1e7),talentCostZAR=num(b.talentCostZAR,0,1e8),monthlyRevenueZAR=Math.round(chargeGBP*fxRate),grossContributionZAR=Math.round(monthlyRevenueZAR-talentCostZAR),marginPct=monthlyRevenueZAR?Math.round(grossContributionZAR/monthlyRevenueZAR*1000)/10:0;const record:ManagedSeat={talentName,clientName,role,chargeGBP,talentCostZAR,fxRate,monthlyRevenueZAR,grossContributionZAR,marginPct,status:clean(b.status,30)||'active',createdAt:new Date().toISOString()};const [id]=await db.add(table('agency-seats',await orgOwnerId(ctx.user!)),[record]);return id?json({item:{id,...record}},201):error('Unable to save managed seat.',500)}],
 ...accessRoutes,
 ...intakeRoutes,
 ...milestone3Routes,
 ...milestone4Routes,
 ...milestone5Routes,
 ...adzunaRoutes,
 ...milestone6Routes,
})

export const handler=async(event:any)=>{const path=event.rawPath||event.requestContext?.http?.path||event.path||'',method=event.requestContext?.http?.method||event.httpMethod||'',requiredRole=requiredAccountRoleForPath(path),permission=permissionForPath(method,path);if(requiredRole||permission){const user=await auth.getUser(event);if(user&&requiredRole){const accountRole=await getPrimaryAccountRole(user.userId);if(accountRole?.status!=='active'||accountRole.role!==requiredRole)return error(`This account does not have ${requiredRole} workspace access.`,403)}if(user&&permission){const access=await getOrgAccess(user);if(!hasOrgPermission(access,permission))return error(`Your ${access.role} role does not permit this operation.`,403)}}return routed(event)}