import { db, error, json, requireAuth } from '@appdeploy/sdk';
import { appendAudit, getCanonicalAgencyOwnerId, getOrgAccess, hasOrgPermission } from './org';

type RoleInput={company:string;email:string;role:string;hires:number;notes:string;createdAt:string};
type TalentInput={name:string;email:string;role:string;experience:string;availability:string;linkedin:string;createdAt:string};
type RoleLead=RoleInput&{sourceId:string;status:string;accountId:string;roleId:string;updatedAt:string};
type TalentLead=TalentInput&{sourceId:string;status:string;candidateId:string;updatedAt:string};
type GlobalRole=RoleInput&{status?:string};
type GlobalTalent=TalentInput&{stage?:string};
type Account={company:string;contactName:string;contactEmail:string;country:string;segment:string;stage:string;estimatedSeats:number;estimatedMonthlyGBP:number;nextAction:string;nextActionDate:string;notes:string;createdAt:string;updatedAt:string};
type Role={accountId:string;clientName:string;role:string;seniority:string;hires:number;model:string;status:string;notes:string;requirements:string;requiredSkills:string;systems:string;minYears:number;minScore:number;createdAt:string};
type Candidate={name:string;email:string;role:string;years:number;city:string;availability:string;skills:string;summary:string;stage:string;technical:number;communication:number;experienceFit:number;remoteReadiness:number;references:number;score:number;createdAt:string};
const table=(name:string,id:string)=>`${name}:${id}`;
const now=()=>new Date().toISOString();
const yearsFrom=(v:string)=>Math.max(0,Math.min(60,Number(v.match(/\d+/)?.[0]||0)));
async function scopedHasSource<T extends{sourceId:string}>(name:string,sourceId:string){const{items}=await db.list<T>(name,{limit:150});return items.some(x=>x.sourceId===sourceId)}
export async function mirrorRoleLead(sourceId:string,input:RoleInput){const ownerId=await getCanonicalAgencyOwnerId();if(!ownerId)return false;const t=table('agency-public-role-intake',ownerId);if(await scopedHasSource<RoleLead>(t,sourceId))return true;const stamp=now(),[id]=await db.add(t,[{...input,sourceId,status:'new',accountId:'',roleId:'',updatedAt:stamp}]);return Boolean(id)}
export async function mirrorTalentLead(sourceId:string,input:TalentInput){const ownerId=await getCanonicalAgencyOwnerId();if(!ownerId)return false;const t=table('agency-public-talent-intake',ownerId);if(await scopedHasSource<TalentLead>(t,sourceId))return true;const stamp=now(),[id]=await db.add(t,[{...input,sourceId,status:'new',candidateId:'',updatedAt:stamp}]);return Boolean(id)}
async function syncPublicIntake(ownerId:string){const canonical=await getCanonicalAgencyOwnerId();if(!canonical||canonical!==ownerId)return;const rt=table('agency-public-role-intake',ownerId),tt=table('agency-public-talent-intake',ownerId),[globalRoles,globalTalent,scopedRoles,scopedTalent]=await Promise.all([db.list<GlobalRole>('public-role-leads',{limit:150}),db.list<GlobalTalent>('talent-applications',{limit:150}),db.list<RoleLead>(rt,{limit:150}),db.list<TalentLead>(tt,{limit:150})]),roleSeen=new Set(scopedRoles.items.map(x=>x.sourceId)),talentSeen=new Set(scopedTalent.items.map(x=>x.sourceId)),stamp=now(),roleAdds=globalRoles.items.filter(x=>!roleSeen.has(x.id)).map(x=>({sourceId:x.id,company:x.company,email:x.email,role:x.role,hires:x.hires,notes:x.notes,createdAt:x.createdAt,status:'new',accountId:'',roleId:'',updatedAt:stamp})),talentAdds=globalTalent.items.filter(x=>!talentSeen.has(x.id)).map(x=>({sourceId:x.id,name:x.name,email:x.email,role:x.role,experience:x.experience,availability:x.availability,linkedin:x.linkedin,createdAt:x.createdAt,status:'new',candidateId:'',updatedAt:stamp}));if(roleAdds.length)await db.add(rt,roleAdds);if(talentAdds.length)await db.add(tt,talentAdds)}
async function access(ctxUser:{userId:string;email?:string;name?:string},permission:string){const a=await getOrgAccess(ctxUser);return hasOrgPermission(a,permission)?a:null}
export const intakeRoutes={
 'GET /api/command/intake':[requireAuth(),async ctx=>{const a=await access(ctx.user!,'crm');if(!a)return error('Your role cannot review public intake.',403);await syncPublicIntake(a.ownerId);const[roles,talent]=await Promise.all([db.list<RoleLead>(table('agency-public-role-intake',a.ownerId),{limit:150}),db.list<TalentLead>(table('agency-public-talent-intake',a.ownerId),{limit:150})]),roleLeads=[...roles.items].sort((x,y)=>y.createdAt.localeCompare(x.createdAt)),talentLeads=[...talent.items].sort((x,y)=>y.createdAt.localeCompare(x.createdAt));return json({roleLeads,talentLeads,metrics:{roleLeads:roleLeads.length,talentLeads:talentLeads.length,waiting:roleLeads.filter(x=>x.status==='new').length+talentLeads.filter(x=>x.status==='new').length,converted:roleLeads.filter(x=>x.status==='converted').length+talentLeads.filter(x=>x.status==='converted').length}})}],
 'POST /api/command/intake/roles/:id/convert':[requireAuth(),async ctx=>{const a=await access(ctx.user!,'crm');if(!a)return error('Your role cannot convert employer intake.',403);const it=table('agency-public-role-intake',a.ownerId),[lead]=await db.get<RoleLead>(it,[ctx.params.id]);if(!lead)return error('Employer intake not found.',404);if(lead.status==='converted'&&lead.roleId)return json({ok:true,alreadyConverted:true,accountId:lead.accountId,roleId:lead.roleId});const stamp=now(),at=table('agency-accounts',a.ownerId),{items:accounts}=await db.list<Account>(at,{limit:100});let accountId=accounts.find(x=>x.company.toLowerCase()===lead.company.toLowerCase())?.id||'';if(!accountId){[accountId]=await db.add(at,[{company:lead.company,contactName:'',contactEmail:lead.email,country:'United Kingdom',segment:'Website hiring enquiry',stage:'qualified',estimatedSeats:lead.hires,estimatedMonthlyGBP:Math.max(1,lead.hires)*2300,nextAction:'Review role brief and contact employer',nextActionDate:'',notes:`Public role enquiry · ${lead.role}`,createdAt:stamp,updatedAt:stamp}]);if(!accountId)return error('Unable to create CRM account.',500)}const roleTable=table('agency-roles',a.ownerId),{items:existingRoles}=await db.list<Role>(roleTable,{limit:100});let roleId=existingRoles.find(x=>x.accountId===accountId&&x.role.toLowerCase()===lead.role.toLowerCase()&&x.status!=='closed')?.id||'';if(!roleId){[roleId]=await db.add(roleTable,[{accountId,clientName:lead.company,role:lead.role,seniority:'To confirm',hires:lead.hires,model:'Managed Talent',status:'active',notes:'Created from SouthBridge website employer intake.',requirements:lead.notes,requiredSkills:'',systems:'',minYears:0,minScore:75,createdAt:stamp}]);if(!roleId)return error('Unable to create qualified role.',500)}const record={...lead,status:'converted',accountId,roleId,updatedAt:stamp},[ok]=await db.update(it,[{id:ctx.params.id,record}]);if(!ok)return error('Unable to update employer intake.',500);await appendAudit(a.ownerId,ctx.user!,'intake.employer.converted','role_lead',ctx.params.id,`${accountId}:${roleId}`);return json({ok:true,accountId,roleId,item:{id:ctx.params.id,...record}})}],
 'POST /api/command/intake/talent/:id/convert':[requireAuth(),async ctx=>{const a=await access(ctx.user!,'talent');if(!a)return error('Your role cannot convert talent intake.',403);const it=table('agency-public-talent-intake',a.ownerId),[lead]=await db.get<TalentLead>(it,[ctx.params.id]);if(!lead)return error('Talent intake not found.',404);if(lead.status==='converted'&&lead.candidateId)return json({ok:true,alreadyConverted:true,candidateId:lead.candidateId});const ct=table('agency-candidates',a.ownerId),{items}=await db.list<Candidate>(ct,{limit:120}),existing=items.find(x=>x.email&&x.email.toLowerCase()===lead.email.toLowerCase());let candidateId=existing?.id||'';if(!candidateId){[candidateId]=await db.add(ct,[{name:lead.name,email:lead.email,role:lead.role,years:yearsFrom(lead.experience),city:'',availability:lead.availability,skills:'',summary:'Website talent application. Complete screening, evidence review and SouthBridge assessment before shortlist.',stage:'screening',technical:0,communication:0,experienceFit:0,remoteReadiness:0,references:0,score:0,createdAt:now()}]);if(!candidateId)return error('Unable to add talent to screening bench.',500)}const record={...lead,status:'converted',candidateId,updatedAt:now()},[ok]=await db.update(it,[{id:ctx.params.id,record}]);if(!ok)return error('Unable to update talent intake.',500);await appendAudit(a.ownerId,ctx.user!,'intake.talent.converted','talent_lead',ctx.params.id,candidateId);return json({ok:true,candidateId,alreadyExists:Boolean(existing),item:{id:ctx.params.id,...record}})}],
};
