import { db, error, json, requireAuth } from '@appdeploy/sdk';
import { orgOwnerId } from './org';

type Account={company:string;contactName:string;contactEmail:string;country:string;segment:string;stage:string;estimatedSeats:number;estimatedMonthlyGBP:number;nextAction:string;nextActionDate:string;notes:string;createdAt:string;updatedAt:string};
type Candidate={name:string;email:string;role:string;years:number;city:string;availability:string;skills:string;summary:string;stage:string;technical:number;communication:number;experienceFit:number;remoteReadiness:number;references:number;score:number;createdAt:string};
type Role={accountId?:string;clientName:string;role:string;seniority:string;hires:number;model:string;status:string;notes:string;requirements?:string;requiredSkills?:string;systems?:string;minYears?:number;minScore?:number;createdAt:string};
type Interview={candidateId:string;candidateName:string;roleId:string;role:string;clientName:string;scheduledAt:string;timezone:string;status:string;outcome:string;notes:string;createdAt:string;updatedAt:string};
type Engagement={candidateId:string;candidateName:string;roleId:string;role:string;clientName:string;model:string;startDate:string;contractStatus:string;identityStatus:string;clientAccessStatus:string;equipmentStatus:string;payrollStatus:string;status:string;placementFeeGBP:number;chargeGBP:number;talentCostZAR:number;fxRate:number;activatedRef?:string;notes:string;createdAt:string;updatedAt:string};
type Invoice={clientName:string;period:string;amountZAR:number;dueDate:string;status:string;reference:string;createdAt:string;updatedAt:string};
type Payroll={talentName:string;period:string;amountZAR:number;payDate:string;status:string;reference:string;createdAt:string;updatedAt:string};
type Seat={talentName:string;clientName:string;role:string;chargeGBP:number;talentCostZAR:number;fxRate:number;monthlyRevenueZAR:number;grossContributionZAR:number;marginPct:number;status:string;createdAt:string};
type Placement={candidateName:string;clientName:string;role:string;model:string;feeGBP:number;fxRate:number;feeZAR:number;status:string;createdAt:string};

const clean=(v:unknown,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
const num=(v:unknown,min=0,max=1e9)=>Math.max(min,Math.min(max,Number(v)||0));
const emailOk=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const table=(name:string,uid:string)=>`${name}:${uid}`;
const words=(v:string)=>new Set(v.toLowerCase().split(/[^a-z0-9+#.]+/).map(x=>x.trim()).filter(x=>x.length>1));
const now=()=>new Date().toISOString();
const period=()=>new Date().toISOString().slice(0,7);
const dueIn=(days:number)=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);

export const milestone3Routes={
 'GET /api/command/overview':[requireAuth(),async ctx=>{const uid=(await orgOwnerId(ctx.user!));const [accounts,candidates,roles,interviews,engagements,invoices,payroll,seats,placements]=await Promise.all([db.list<Account>(table('agency-accounts',uid),{limit:80}),db.list<Candidate>(table('agency-candidates',uid),{limit:80}),db.list<Role>(table('agency-roles',uid),{limit:80}),db.list<Interview>(table('agency-interviews',uid),{limit:80}),db.list<Engagement>(table('agency-engagements',uid),{limit:80}),db.list<Invoice>(table('agency-invoices',uid),{limit:100}),db.list<Payroll>(table('agency-payroll',uid),{limit:100}),db.list<Seat>(table('agency-seats',uid),{limit:80}),db.list<Placement>(table('agency-placements',uid),{limit:80})]);const activeSeats=seats.items.filter(x=>x.status==='active'),mrr=activeSeats.reduce((a,x)=>a+x.monthlyRevenueZAR,0),gp=activeSeats.reduce((a,x)=>a+x.grossContributionZAR,0),receivables=invoices.items.filter(x=>!['paid','void'].includes(x.status)).reduce((a,x)=>a+x.amountZAR,0),payrollDue=payroll.items.filter(x=>x.status!=='paid').reduce((a,x)=>a+x.amountZAR,0),pipelineGBP=accounts.items.filter(x=>!['won','lost'].includes(x.stage)).reduce((a,x)=>a+x.estimatedMonthlyGBP,0);return json({accounts:accounts.items,candidates:candidates.items,roles:roles.items,interviews:interviews.items,engagements:engagements.items,invoices:invoices.items,payroll:payroll.items,seats:seats.items,placements:placements.items,metrics:{openAccounts:accounts.items.filter(x=>!['won','lost'].includes(x.stage)).length,pipelineGBP,activeRoles:roles.items.filter(x=>x.status!=='closed').length,scheduledInterviews:interviews.items.filter(x=>x.status==='scheduled').length,onboarding:engagements.items.filter(x=>x.status!=='active').length,activeSeats:activeSeats.length,mrr,gp,receivables,payrollDue,ledgerCoverage:receivables-payrollDue}})}],
 'POST /api/command/accounts':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<Account>,company=clean(b.company,120),contactEmail=clean(b.contactEmail,160);if(!company||!emailOk(contactEmail))return error('Company and valid contact email are required.',400);const stamp=now(),record:Account={company,contactName:clean(b.contactName,120),contactEmail,country:clean(b.country,80)||'United Kingdom',segment:clean(b.segment,80)||'Accounting firm',stage:clean(b.stage,30)||'prospect',estimatedSeats:num(b.estimatedSeats,0,500),estimatedMonthlyGBP:num(b.estimatedMonthlyGBP,0,1e7),nextAction:clean(b.nextAction,300),nextActionDate:clean(b.nextActionDate,30),notes:clean(b.notes,1500),createdAt:stamp,updatedAt:stamp};const [id]=await db.add(table('agency-accounts',(await orgOwnerId(ctx.user!))),[record]);return id?json({item:{id,...record}},201):error('Unable to create CRM account.',500)}],
 'PUT /api/command/accounts/:id':[requireAuth(),async ctx=>{const t=table('agency-accounts',(await orgOwnerId(ctx.user!))),[existing]=await db.get<Account>(t,[ctx.params.id]);if(!existing)return error('Account not found.',404);const b=(ctx.body||{}) as Partial<Account>,record:Account={...existing,stage:b.stage===undefined?existing.stage:clean(b.stage,30),nextAction:b.nextAction===undefined?existing.nextAction:clean(b.nextAction,300),nextActionDate:b.nextActionDate===undefined?existing.nextActionDate:clean(b.nextActionDate,30),estimatedSeats:b.estimatedSeats===undefined?existing.estimatedSeats:num(b.estimatedSeats,0,500),estimatedMonthlyGBP:b.estimatedMonthlyGBP===undefined?existing.estimatedMonthlyGBP:num(b.estimatedMonthlyGBP,0,1e7),notes:b.notes===undefined?existing.notes:clean(b.notes,1500),updatedAt:now()};const [ok]=await db.update(t,[{id:ctx.params.id,record}]);return ok?json({item:{id:ctx.params.id,...record}}):error('Unable to update CRM account.',500)}],
 'POST /api/command/roles':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<Role> & {accountId?:string},accountId=clean(b.accountId,100),role=clean(b.role,100);if(!accountId||!role)return error('CRM account and role are required.',400);const [account]=await db.get<Account>(table('agency-accounts',(await orgOwnerId(ctx.user!))),[accountId]);if(!account)return error('CRM account not found.',404);const record:Role={accountId,clientName:account.company,role,seniority:clean(b.seniority,50)||'Mid-level',hires:num(b.hires,1,50)||1,model:clean(b.model,40)||'Direct Hire',status:'active',notes:clean(b.notes,1200),requirements:clean(b.requirements,1500),requiredSkills:clean(b.requiredSkills,700),systems:clean(b.systems,500),minYears:num(b.minYears,0,30),minScore:num(b.minScore,0,100)||75,createdAt:now()};const [id]=await db.add(table('agency-roles',(await orgOwnerId(ctx.user!))),[record]);return id?json({item:{id,...record}},201):error('Unable to create role.',500)}],
 'GET /api/command/roles/:id/matches':[requireAuth(),async ctx=>{const uid=(await orgOwnerId(ctx.user!)),[role]=await db.get<Role>(table('agency-roles',uid),[ctx.params.id]);if(!role)return error('Role not found.',404);const {items}=await db.list<Candidate>(table('agency-candidates',uid),{limit:80}),required=words(`${role.requiredSkills||''} ${role.systems||''}`),roleWords=words(role.role),minYears=role.minYears||0,minScore=role.minScore||0;const matches=items.map(c=>{const candidateWords=words(`${c.role} ${c.skills} ${c.summary}`),skillHits=[...required].filter(x=>candidateWords.has(x)),roleHit=c.role.toLowerCase()===role.role.toLowerCase()?25:[...roleWords].some(x=>candidateWords.has(x))?15:0,scorePart=Math.round((c.score||0)*.25),yearsPart=minYears===0?20:Math.min(20,Math.round((c.years/minYears)*20)),skillsPart=required.size===0?20:Math.round(skillHits.length/required.size*20),remotePart=Math.round((c.remoteReadiness||0)*.1),matchScore=Math.min(100,roleHit+scorePart+yearsPart+skillsPart+remotePart),eligible=(c.score||0)>=minScore&&c.years>=minYears;const reasons=[roleHit===25?'Exact role alignment':roleHit?'Adjacent role alignment':'Role needs review',`${c.years} years experience`,`SouthBridge Score ${c.score}`,required.size?`${skillHits.length}/${required.size} required skill signals`:'No hard skill filter'];return {...c,matchScore,eligible,reasons}}).sort((a,b)=>b.matchScore-a.matchScore);return json({role,matches:matches.slice(0,30)})}],
 'POST /api/command/interviews':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as {candidateId?:string;roleId?:string;scheduledAt?:string;timezone?:string;notes?:string},candidateId=clean(b.candidateId,100),roleId=clean(b.roleId,100),scheduledAt=clean(b.scheduledAt,80);if(!candidateId||!roleId||!scheduledAt)return error('Candidate, role and interview time are required.',400);const uid=(await orgOwnerId(ctx.user!)),[candidate]=await db.get<Candidate>(table('agency-candidates',uid),[candidateId]),[role]=await db.get<Role>(table('agency-roles',uid),[roleId]);if(!candidate||!role)return error('Candidate or role not found.',404);const stamp=now(),record:Interview={candidateId,candidateName:candidate.name,roleId,role:role.role,clientName:role.clientName,scheduledAt,timezone:clean(b.timezone,80)||'Europe/London',status:'scheduled',outcome:'',notes:clean(b.notes,1000),createdAt:stamp,updatedAt:stamp};const [id]=await db.add(table('agency-interviews',uid),[record]);return id?json({item:{id,...record}},201):error('Unable to schedule interview.',500)}],
 'PUT /api/command/interviews/:id':[requireAuth(),async ctx=>{const t=table('agency-interviews',(await orgOwnerId(ctx.user!))),[existing]=await db.get<Interview>(t,[ctx.params.id]);if(!existing)return error('Interview not found.',404);const b=(ctx.body||{}) as Partial<Interview>,status=b.status===undefined?existing.status:clean(b.status,30);if(!['scheduled','completed','cancelled','no-show'].includes(status))return error('Invalid interview status.',400);const record:Interview={...existing,status,outcome:b.outcome===undefined?existing.outcome:clean(b.outcome,500),notes:b.notes===undefined?existing.notes:clean(b.notes,1000),scheduledAt:b.scheduledAt===undefined?existing.scheduledAt:clean(b.scheduledAt,80),updatedAt:now()};const [ok]=await db.update(t,[{id:ctx.params.id,record}]);return ok?json({item:{id:ctx.params.id,...record}}):error('Unable to update interview.',500)}],
 'POST /api/command/engagements':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<Engagement>,candidateId=clean(b.candidateId,100),roleId=clean(b.roleId,100),startDate=clean(b.startDate,30);if(!candidateId||!roleId||!startDate)return error('Candidate, role and start date are required.',400);const uid=(await orgOwnerId(ctx.user!)),[candidate]=await db.get<Candidate>(table('agency-candidates',uid),[candidateId]),[role]=await db.get<Role>(table('agency-roles',uid),[roleId]);if(!candidate||!role)return error('Candidate or role not found.',404);const stamp=now(),record:Engagement={candidateId,candidateName:candidate.name,roleId,role:role.role,clientName:role.clientName,model:role.model,startDate,contractStatus:'draft',identityStatus:'pending',clientAccessStatus:'pending',equipmentStatus:'not-required',payrollStatus:role.model==='Direct Hire'?'not-required':'pending',status:'preboarding',placementFeeGBP:num(b.placementFeeGBP,0,1e7),chargeGBP:num(b.chargeGBP,0,1e7),talentCostZAR:num(b.talentCostZAR,0,1e8),fxRate:num(b.fxRate,1,1000)||24,notes:clean(b.notes,1200),createdAt:stamp,updatedAt:stamp};const [id]=await db.add(table('agency-engagements',uid),[record]);return id?json({item:{id,...record}},201):error('Unable to create onboarding record.',500)}],
 'PUT /api/command/engagements/:id':[requireAuth(),async ctx=>{const t=table('agency-engagements',(await orgOwnerId(ctx.user!))),[existing]=await db.get<Engagement>(t,[ctx.params.id]);if(!existing)return error('Engagement not found.',404);const b=(ctx.body||{}) as Partial<Engagement>,allowed=(value:string,current:string,options:string[])=>options.includes(value)?value:current,record:Engagement={...existing,contractStatus:b.contractStatus===undefined?existing.contractStatus:allowed(clean(b.contractStatus,30),existing.contractStatus,['draft','sent','signed']),identityStatus:b.identityStatus===undefined?existing.identityStatus:allowed(clean(b.identityStatus,30),existing.identityStatus,['pending','verified']),clientAccessStatus:b.clientAccessStatus===undefined?existing.clientAccessStatus:allowed(clean(b.clientAccessStatus,30),existing.clientAccessStatus,['pending','ready']),equipmentStatus:b.equipmentStatus===undefined?existing.equipmentStatus:allowed(clean(b.equipmentStatus,30),existing.equipmentStatus,['not-required','pending','ready']),payrollStatus:b.payrollStatus===undefined?existing.payrollStatus:allowed(clean(b.payrollStatus,30),existing.payrollStatus,['not-required','pending','ready']),notes:b.notes===undefined?existing.notes:clean(b.notes,1200),updatedAt:now()};const [ok]=await db.update(t,[{id:ctx.params.id,record}]);return ok?json({item:{id:ctx.params.id,...record}}):error('Unable to update onboarding.',500)}],
 'POST /api/command/engagements/:id/activate':[requireAuth(),async ctx=>{const uid=(await orgOwnerId(ctx.user!)),t=table('agency-engagements',uid),[existing]=await db.get<Engagement>(t,[ctx.params.id]);if(!existing)return error('Engagement not found.',404);if(existing.activatedRef)return json({ok:true,alreadyActive:true,reference:existing.activatedRef});const managed=existing.model!=='Direct Hire',ready=existing.contractStatus==='signed'&&existing.identityStatus==='verified'&&existing.clientAccessStatus==='ready'&&(!managed||existing.payrollStatus==='ready');if(!ready)return error('Complete contract, identity, client access and payroll readiness before activation.',409);let reference='';if(managed){const monthlyRevenueZAR=Math.round(existing.chargeGBP*existing.fxRate),grossContributionZAR=Math.round(monthlyRevenueZAR-existing.talentCostZAR),marginPct=monthlyRevenueZAR?Math.round(grossContributionZAR/monthlyRevenueZAR*1000)/10:0;const [seatId]=await db.add(table('agency-seats',uid),[{talentName:existing.candidateName,clientName:existing.clientName,role:existing.role,chargeGBP:existing.chargeGBP,talentCostZAR:existing.talentCostZAR,fxRate:existing.fxRate,monthlyRevenueZAR,grossContributionZAR,marginPct,status:'active',createdAt:now()}]);if(!seatId)return error('Unable to activate managed seat.',500);reference=`SEAT-${seatId.slice(0,8).toUpperCase()}`;const stamp=now();await db.add(table('agency-invoices',uid),[{clientName:existing.clientName,period:period(),amountZAR:monthlyRevenueZAR,dueDate:dueIn(7),status:'draft',reference,createdAt:stamp,updatedAt:stamp}]);await db.add(table('agency-payroll',uid),[{talentName:existing.candidateName,period:period(),amountZAR:existing.talentCostZAR,payDate:dueIn(3),status:'pending',reference,createdAt:stamp,updatedAt:stamp}])}else{const feeZAR=Math.round(existing.placementFeeGBP*existing.fxRate),[placementId]=await db.add(table('agency-placements',uid),[{candidateName:existing.candidateName,clientName:existing.clientName,role:existing.role,model:'Direct Hire',feeGBP:existing.placementFeeGBP,fxRate:existing.fxRate,feeZAR,status:'placed',createdAt:now()}]);if(!placementId)return error('Unable to activate placement.',500);reference=`PLACE-${placementId.slice(0,8).toUpperCase()}`;const stamp=now();await db.add(table('agency-invoices',uid),[{clientName:existing.clientName,period:period(),amountZAR:feeZAR,dueDate:dueIn(7),status:'draft',reference,createdAt:stamp,updatedAt:stamp}])}const record:Engagement={...existing,status:'active',activatedRef:reference,updatedAt:now()};await db.update(t,[{id:ctx.params.id,record}]);return json({ok:true,reference,record})}],
 'POST /api/command/invoices':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<Invoice>,clientName=clean(b.clientName,120),periodValue=clean(b.period,20),amountZAR=num(b.amountZAR,0,1e9);if(!clientName||!periodValue||!amountZAR)return error('Client, period and invoice amount are required.',400);const stamp=now(),record:Invoice={clientName,period:periodValue,amountZAR,dueDate:clean(b.dueDate,30),status:'draft',reference:clean(b.reference,80),createdAt:stamp,updatedAt:stamp};const [id]=await db.add(table('agency-invoices',(await orgOwnerId(ctx.user!))),[record]);return id?json({item:{id,...record}},201):error('Unable to add invoice ledger record.',500)}],
 'PUT /api/command/invoices/:id':[requireAuth(),async ctx=>{const t=table('agency-invoices',(await orgOwnerId(ctx.user!))),[existing]=await db.get<Invoice>(t,[ctx.params.id]);if(!existing)return error('Invoice record not found.',404);const status=clean((ctx.body as {status?:string}||{}).status,30);if(!['draft','sent','paid','overdue','void'].includes(status))return error('Invalid invoice status.',400);const record={...existing,status,updatedAt:now()};const [ok]=await db.update(t,[{id:ctx.params.id,record}]);return ok?json({item:{id:ctx.params.id,...record}}):error('Unable to update invoice.',500)}],
 'POST /api/command/payroll':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<Payroll>,talentName=clean(b.talentName,120),periodValue=clean(b.period,20),amountZAR=num(b.amountZAR,0,1e9);if(!talentName||!periodValue||!amountZAR)return error('Talent, period and payroll amount are required.',400);const stamp=now(),record:Payroll={talentName,period:periodValue,amountZAR,payDate:clean(b.payDate,30),status:'pending',reference:clean(b.reference,80),createdAt:stamp,updatedAt:stamp};const [id]=await db.add(table('agency-payroll',(await orgOwnerId(ctx.user!))),[record]);return id?json({item:{id,...record}},201):error('Unable to add payroll ledger record.',500)}],
 'PUT /api/command/payroll/:id':[requireAuth(),async ctx=>{const t=table('agency-payroll',(await orgOwnerId(ctx.user!))),[existing]=await db.get<Payroll>(t,[ctx.params.id]);if(!existing)return error('Payroll record not found.',404);const status=clean((ctx.body as {status?:string}||{}).status,30);if(!['pending','approved','paid','held'].includes(status))return error('Invalid payroll status.',400);const record={...existing,status,updatedAt:now()};const [ok]=await db.update(t,[{id:ctx.params.id,record}]);return ok?json({item:{id:ctx.params.id,...record}}):error('Unable to update payroll.',500)}],
};
