import { db, error, json, notifications, requireAuth, storage } from '@appdeploy/sdk';
import { appendAudit, getOrgAccess, orgOwnerId, rolePermissions } from './org';

type Engagement={candidateName:string;role:string;clientName:string;model:string;startDate:string;contractStatus:string;identityStatus:string;clientAccessStatus:string;equipmentStatus:string;payrollStatus:string;status:string;activatedRef?:string};
type Seat={talentName:string;clientName:string;role:string;monthlyRevenueZAR:number;talentCostZAR:number;grossContributionZAR:number;status:string};
type Invoice={clientName:string;period:string;amountZAR:number;dueDate:string;status:string;reference:string;createdAt:string;updatedAt:string};
type Payroll={talentName:string;period:string;amountZAR:number;payDate:string;status:string;reference:string;createdAt:string;updatedAt:string};
type Timesheet={seatId:string;talentName:string;clientName:string;period:string;hours:number;billableHours:number;status:string;notes:string;createdAt:string;updatedAt:string};
type Performance={seatId:string;talentName:string;clientName:string;period:string;quality:number;communication:number;reliability:number;clientSatisfaction:number;score:number;status:string;notes:string;createdAt:string;updatedAt:string};
type Compliance={engagementId:string;candidateName:string;clientName:string;dataConsent:string;identity:string;contract:string;remoteSetup:string;clientAccess:string;payroll:string;status:string;notes:string;updatedAt:string};
type Pack={engagementId:string;candidateName:string;clientName:string;role:string;version:number;status:string;documents:{name:string;path:string}[];createdAt:string};
type TeamPolicy={email:string;role:string;status:string;permissions:string[];createdAt:string};
type Audit={sequence:number;action:string;entityType:string;entityId:string;detail:string;actorId:string;actorEmail:string;createdAt:string;previousHash:string;hash:string};
const clean=(v:unknown,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
const num=(v:unknown,min=0,max=1e9)=>Math.max(min,Math.min(max,Number(v)||0));
const table=(name:string,uid:string)=>`${name}:${uid}`;
const now=()=>new Date().toISOString();
const dueIn=(d:number)=>new Date(Date.now()+d*86400000).toISOString().slice(0,10);
const roles=rolePermissions;
const score4=(a:number,b:number,c:number,d:number)=>Math.round((a+b+c+d)/4);
export const milestone4Routes={
 'GET /api/control/overview':[requireAuth(),async ctx=>{const access=await getOrgAccess(ctx.user!),uid=access.ownerId;const [engagements,seats,invoices,payroll,timesheets,performance,compliance,packs,policies,audits]=await Promise.all([db.list<Engagement>(table('agency-engagements',uid),{limit:80}),db.list<Seat>(table('agency-seats',uid),{limit:80}),db.list<Invoice>(table('agency-invoices',uid),{limit:120}),db.list<Payroll>(table('agency-payroll',uid),{limit:120}),db.list<Timesheet>(table('agency-timesheets',uid),{limit:120}),db.list<Performance>(table('agency-performance',uid),{limit:120}),db.list<Compliance>(table('agency-compliance',uid),{limit:100}),db.list<Pack>(table('agency-document-packs',uid),{limit:80}),db.list<TeamPolicy>(table('agency-team-policies',uid),{limit:50}),db.list<Audit>(table('agency-audit',uid),{limit:100})]);const active=seats.items.filter(x=>x.status==='active'),unpaid=invoices.items.filter(x=>!['paid','void'].includes(x.status)).reduce((a,x)=>a+x.amountZAR,0),payrollDue=payroll.items.filter(x=>x.status!=='paid').reduce((a,x)=>a+x.amountZAR,0),approvedHours=timesheets.items.filter(x=>x.status==='approved').reduce((a,x)=>a+x.billableHours,0),avgPerformance=performance.items.length?Math.round(performance.items.reduce((a,x)=>a+x.score,0)/performance.items.length):0,complianceReady=compliance.items.filter(x=>x.status==='ready').length;return json({authority:{role:access.role,userId:ctx.user!.userId,email:ctx.user!.email||'',permissions:access.permissions},roleDefinitions:roles,engagements:engagements.items,seats:seats.items,invoices:invoices.items,payroll:payroll.items,timesheets:timesheets.items,performance:performance.items,compliance:compliance.items,packs:packs.items,policies:policies.items,audits:[...audits.items].sort((a,b)=>b.sequence-a.sequence),metrics:{activeSeats:active.length,unpaid,payrollDue,approvedHours,avgPerformance,complianceReady,complianceTotal:compliance.items.length,documentPacks:packs.items.length,auditEvents:audits.items.length}})}],
 'POST /api/control/team-policies':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as {email?:string;role?:string},email=clean(b.email,160),role=clean(b.role,40);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!roles[role]||role==='Owner')return error('Valid email and staff role are required.',400);const record:TeamPolicy={email,role,status:'pending_identity_link',permissions:roles[role],createdAt:now()};const [id]=await db.add(table('agency-team-policies',(await orgOwnerId(ctx.user!))),[record]);if(!id)return error('Unable to save role policy.',500);await appendAudit((await orgOwnerId(ctx.user!)),ctx.user!,'policy.created','team_policy',id,`${email}:${role}`);return json({item:{id,...record}},201)}],
 'POST /api/control/compliance':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<Compliance>,engagementId=clean(b.engagementId,100);if(!engagementId)return error('Engagement is required.',400);const uid=(await orgOwnerId(ctx.user!)),[e]=await db.get<Engagement>(table('agency-engagements',uid),[engagementId]);if(!e)return error('Engagement not found.',404);const val=(x:unknown)=>['pending','complete','not-required'].includes(clean(x,30))?clean(x,30):'pending',managed=e.model!=='Direct Hire',record:Compliance={engagementId,candidateName:e.candidateName,clientName:e.clientName,dataConsent:val(b.dataConsent),identity:e.identityStatus==='verified'?'complete':val(b.identity),contract:e.contractStatus==='signed'?'complete':val(b.contract),remoteSetup:val(b.remoteSetup),clientAccess:e.clientAccessStatus==='ready'?'complete':val(b.clientAccess),payroll:managed?(e.payrollStatus==='ready'?'complete':val(b.payroll)):'not-required',status:'pending',notes:clean(b.notes,1000),updatedAt:now()};record.status=[record.dataConsent,record.identity,record.contract,record.remoteSetup,record.clientAccess,record.payroll].every(x=>['complete','not-required'].includes(x))?'ready':'pending';const t=table('agency-compliance',uid),{items}=await db.list<Compliance>(t,{limit:100,filter:{engagementId}});let id=items[0]?.id;if(id)await db.update(t,[{id,record}]);else [id]=await db.add(t,[record]);if(!id)return error('Unable to save compliance control.',500);await appendAudit(uid,ctx.user!,'compliance.updated','engagement',engagementId,record.status);return json({item:{id,...record}})}],
 'POST /api/control/document-packs':[requireAuth(),async ctx=>{const engagementId=clean((ctx.body as {engagementId?:string}||{}).engagementId,100),uid=(await orgOwnerId(ctx.user!));if(!engagementId)return error('Engagement is required.',400);const [e]=await db.get<Engagement>(table('agency-engagements',uid),[engagementId]);if(!e)return error('Engagement not found.',404);const {items}=await db.list<Pack>(table('agency-document-packs',uid),{limit:80,filter:{engagementId}}),version=(items.reduce((m,x)=>Math.max(m,x.version),0)||0)+1,base=`controls/${uid}/${engagementId}/v${version}`,stamp=now(),summary=`SOUTHBRIDGE OPERATIONAL ENGAGEMENT SUMMARY\nVersion ${version}\nGenerated ${stamp}\nClient: ${e.clientName}\nTalent: ${e.candidateName}\nRole: ${e.role}\nModel: ${e.model}\nStart: ${e.startDate}\nStatus: ${e.status}\n\nThis is an operational control document, not a signed legal agreement.`,checklist=`SOUTHBRIDGE CONTROL CHECKLIST\nContract: ${e.contractStatus}\nIdentity: ${e.identityStatus}\nClient access: ${e.clientAccessStatus}\nEquipment: ${e.equipmentStatus}\nPayroll: ${e.payrollStatus}\n`,assignment=`SOUTHBRIDGE WORKFORCE ASSIGNMENT\nClient: ${e.clientName}\nTalent: ${e.candidateName}\nRole: ${e.role}\nEngagement reference: ${e.activatedRef||'Pre-activation'}\n`;const docs=[{name:'Engagement summary',path:`${base}/engagement-summary.txt`,content:summary},{name:'Control checklist',path:`${base}/control-checklist.txt`,content:checklist},{name:'Workforce assignment',path:`${base}/workforce-assignment.txt`,content:assignment}],written=await storage.write(docs.map(d=>({path:d.path,content:d.content,contentType:'text/plain'})));if(written.some(x=>!x))return error('Unable to generate document pack.',500);const record:Pack={engagementId,candidateName:e.candidateName,clientName:e.clientName,role:e.role,version,status:'generated',documents:docs.map(({name,path})=>({name,path})),createdAt:stamp},[id]=await db.add(table('agency-document-packs',uid),[record]);if(!id)return error('Unable to register document pack.',500);await appendAudit(uid,ctx.user!,'documents.generated','engagement',engagementId,`v${version}`);return json({item:{id,...record}},201)}],
 'GET /api/control/document-packs/:id/url':[requireAuth(),async ctx=>{const [p]=await db.get<Pack>(table('agency-document-packs',(await orgOwnerId(ctx.user!))),[ctx.params.id]);if(!p)return error('Document pack not found.',404);const urls=await storage.url(p.documents.map(x=>x.path));return json({documents:p.documents.map((x,i)=>({name:x.name,url:urls[i]?.url||''}))})}],
 'POST /api/control/timesheets':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<Timesheet>,seatId=clean(b.seatId,100),period=clean(b.period,20),uid=(await orgOwnerId(ctx.user!));if(!seatId||!period)return error('Managed seat and period are required.',400);const [seat]=await db.get<Seat>(table('agency-seats',uid),[seatId]);if(!seat||seat.status!=='active')return error('Active managed seat not found.',404);const stamp=now(),record:Timesheet={seatId,talentName:seat.talentName,clientName:seat.clientName,period,hours:num(b.hours,0,744),billableHours:num(b.billableHours,0,744),status:'submitted',notes:clean(b.notes,1000),createdAt:stamp,updatedAt:stamp},[id]=await db.add(table('agency-timesheets',uid),[record]);if(!id)return error('Unable to submit timesheet.',500);await appendAudit(uid,ctx.user!,'timesheet.submitted','seat',seatId,`${period}:${record.billableHours}`);return json({item:{id,...record}},201)}],
 'PUT /api/control/timesheets/:id':[requireAuth(),async ctx=>{const t=table('agency-timesheets',(await orgOwnerId(ctx.user!))),[x]=await db.get<Timesheet>(t,[ctx.params.id]);if(!x)return error('Timesheet not found.',404);const status=clean((ctx.body as {status?:string}||{}).status,30);if(!['submitted','approved','rejected'].includes(status))return error('Invalid timesheet status.',400);const record={...x,status,updatedAt:now()},[ok]=await db.update(t,[{id:ctx.params.id,record}]);if(ok)await appendAudit((await orgOwnerId(ctx.user!)),ctx.user!,'timesheet.status','timesheet',ctx.params.id,status);return ok?json({item:{id:ctx.params.id,...record}}):error('Unable to update timesheet.',500)}],
 'POST /api/control/performance':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Partial<Performance>,seatId=clean(b.seatId,100),period=clean(b.period,20),uid=(await orgOwnerId(ctx.user!));if(!seatId||!period)return error('Managed seat and period are required.',400);const [seat]=await db.get<Seat>(table('agency-seats',uid),[seatId]);if(!seat)return error('Managed seat not found.',404);const q=num(b.quality,0,100),c=num(b.communication,0,100),r=num(b.reliability,0,100),cs=num(b.clientSatisfaction,0,100),stamp=now(),record:Performance={seatId,talentName:seat.talentName,clientName:seat.clientName,period,quality:q,communication:c,reliability:r,clientSatisfaction:cs,score:score4(q,c,r,cs),status:'recorded',notes:clean(b.notes,1000),createdAt:stamp,updatedAt:stamp},[id]=await db.add(table('agency-performance',uid),[record]);if(!id)return error('Unable to save performance review.',500);await appendAudit(uid,ctx.user!,'performance.recorded','seat',seatId,`${period}:${record.score}`);return json({item:{id,...record}},201)}],
 'POST /api/control/billing/run':[requireAuth(),async ctx=>{const uid=(await orgOwnerId(ctx.user!)),period=clean((ctx.body as {period?:string}||{}).period,20)||new Date().toISOString().slice(0,7),[{items:seats},{items:invoices},{items:payroll}]=await Promise.all([db.list<Seat>(table('agency-seats',uid),{limit:80}),db.list<Invoice>(table('agency-invoices',uid),{limit:120}),db.list<Payroll>(table('agency-payroll',uid),{limit:120})]);let invoiceCount=0,payrollCount=0;for(const seat of seats.filter(x=>x.status==='active')){const ref=`CYCLE-${period}-${seat.id.slice(0,8).toUpperCase()}`;if(!invoices.some(x=>x.reference===ref)){const stamp=now();await db.add(table('agency-invoices',uid),[{clientName:seat.clientName,period,amountZAR:seat.monthlyRevenueZAR,dueDate:dueIn(7),status:'draft',reference:ref,createdAt:stamp,updatedAt:stamp}]);invoiceCount++}if(!payroll.some(x=>x.reference===ref)){const stamp=now();await db.add(table('agency-payroll',uid),[{talentName:seat.talentName,period,amountZAR:seat.talentCostZAR,payDate:dueIn(3),status:'pending',reference:ref,createdAt:stamp,updatedAt:stamp}]);payrollCount++}}await appendAudit(uid,ctx.user!,'billing.cycle','finance',period,`${invoiceCount} invoices/${payrollCount} payroll`);await notifications.send({userIds:[uid],notification:{title:'SouthBridge billing cycle prepared',body:`${period}: ${invoiceCount} invoices and ${payrollCount} payroll commitments created.`},data:{kind:'billing-cycle',period}});return json({ok:true,period,invoiceCount,payrollCount})}],
 'POST /api/control/notify-self':[requireAuth(),async ctx=>{const result=await notifications.send({userIds:[ctx.user!.userId],notification:{title:'SouthBridge controls active',body:'Operational notifications are enabled for this device.'},data:{kind:'control-test'}});return json(result)}],
};