import { createHash } from 'node:crypto';
import { db } from '@appdeploy/sdk';

type User={userId:string;email?:string;name?:string};
export type OrgAccess={ownerId:string;role:string;permissions:string[];status:string;orgName:string};
type Membership={ownerId:string;role:string;permissions:string[];status:string;orgName:string;email:string;joinedAt:string;updatedAt:string};
type Audit={sequence:number;action:string;entityType:string;entityId:string;detail:string;actorId:string;actorEmail:string;createdAt:string;previousHash:string;hash:string};
type AuditHead={sequence:number;hash:string};
type CanonicalAgency={ownerId:string;createdAt:string;updatedAt:string};
export const rolePermissions:Record<string,string[]>={Owner:['read','crm','talent','interviews','onboarding','documents','workforce','finance','compliance','audit','roles','billing','settlement','communications'],Recruiter:['read','crm','talent','interviews','communications'],Operations:['read','interviews','onboarding','documents','workforce','compliance','communications'],Finance:['read','finance','audit','billing','settlement'],Viewer:['read']};
const table=(name:string,id:string)=>`${name}:${id}`;
const canonicalTable='agency-canonical-registry';
async function hasLegacyOwnerData(uid:string){const[o,a,c,r,au,p]=await Promise.all([db.list<Record<string,unknown>>(table('agency-opportunities',uid),{limit:1}),db.list<Record<string,unknown>>(table('agency-accounts',uid),{limit:1}),db.list<Record<string,unknown>>(table('agency-candidates',uid),{limit:1}),db.list<Record<string,unknown>>(table('agency-roles',uid),{limit:1}),db.list<Record<string,unknown>>(table('agency-audit',uid),{limit:1}),db.list<Record<string,unknown>>(table('agency-org-profile',uid),{limit:1})]);return[o,a,c,r,au,p].some(x=>x.items.length>0)}
export async function getCanonicalAgencyOwnerId(){const{items}=await db.list<CanonicalAgency>(canonicalTable,{limit:1});return items[0]?.ownerId||''}
async function registerCanonicalAgencyOwner(uid:string){const{items}=await db.list<CanonicalAgency>(canonicalTable,{limit:1});if(items[0])return items[0].ownerId;const stamp=new Date().toISOString(),[id]=await db.add(canonicalTable,[{ownerId:uid,createdAt:stamp,updatedAt:stamp}]);return id?uid:''}
export async function getOrgAccess(user:User):Promise<OrgAccess>{const {items}=await db.list<Membership>(table('agency-org-membership',user.userId),{limit:1}),m=items[0];if(m)return{ownerId:m.ownerId,role:m.role,permissions:m.status==='active'?(rolePermissions[m.role]||[]):[],status:m.status,orgName:m.orgName||'SouthBridge Talent'};const canonical=await getCanonicalAgencyOwnerId();if(canonical===user.userId||await hasLegacyOwnerData(user.userId)){await registerCanonicalAgencyOwner(user.userId);return{ownerId:user.userId,role:'Owner',permissions:rolePermissions.Owner,status:'active',orgName:'SouthBridge Talent'}}return{ownerId:user.userId,role:'None',permissions:[],status:'unregistered',orgName:'SouthBridge Talent'}}
export async function orgOwnerId(user:User){return(await getOrgAccess(user)).ownerId}
export function hasOrgPermission(access:OrgAccess,permission:string){return access.status==='active'&&(access.role==='Owner'||access.permissions.includes(permission))}
export function permissionForPath(method:string,path:string){const p=path.toLowerCase();if(p.startsWith('/api/command/intake/talent'))return'talent';if(p.startsWith('/api/command/intake'))return'crm';if(p.startsWith('/api/command/overview'))return'read';if(p.startsWith('/api/command/accounts'))return'crm';if(p.includes('/api/command/roles/')&&p.endsWith('/matches'))return'talent';if(p.startsWith('/api/command/roles'))return'crm';if(p.startsWith('/api/command/interviews'))return'interviews';if(p.startsWith('/api/command/engagements'))return'onboarding';if(p.startsWith('/api/command/invoices')||p.startsWith('/api/command/payroll'))return'finance';if(p.startsWith('/api/agency/overview'))return'read';if(p.startsWith('/api/agency/candidates')||p.startsWith('/api/agency/shortlists'))return'talent';if(p.startsWith('/api/agency/roles'))return'crm';if(p.startsWith('/api/agency/placements')||p.startsWith('/api/agency/seats'))return'finance';if(p.startsWith('/api/control/overview')||p.startsWith('/api/control/notify-self'))return'read';if(p.startsWith('/api/control/team-policies'))return'roles';if(p.startsWith('/api/control/compliance'))return'compliance';if(p.startsWith('/api/control/document-packs'))return'documents';if(p.startsWith('/api/control/timesheets')||p.startsWith('/api/control/performance'))return'workforce';if(p.startsWith('/api/control/billing'))return'billing';if(p.startsWith('/api/radar/overview'))return'read';if(p.startsWith('/api/radar/import')||p.includes('/api/radar/opportunities/')&&p.endsWith('/crm'))return'crm';if(p.includes('/api/radar/opportunities/')&&p.endsWith('/publish')||p.startsWith('/api/radar/interests/'))return'talent';return null}
export async function appendAudit(ownerId:string,actor:User,action:string,entityType:string,entityId:string,detail=''){const auditTable=table('agency-audit',ownerId),headTable=table('agency-audit-head',ownerId);let {items:heads}=await db.list<AuditHead>(headTable,{limit:1}),head=heads[0];if(!head){const {items}=await db.list<Audit>(auditTable,{limit:100}),last=[...items].sort((a,b)=>b.sequence-a.sequence)[0],seed:AuditHead={sequence:last?.sequence||0,hash:last?.hash||'GENESIS'},[id]=await db.add(headTable,[seed]);head=id?{id,...seed}:seed as AuditHead&{id?:string}}const sequence=(head.sequence||0)+1,createdAt=new Date().toISOString(),previousHash=head.hash||'GENESIS',payload=`${sequence}|${action}|${entityType}|${entityId}|${detail}|${actor.userId}|${createdAt}|${previousHash}`,hash=createHash('sha256').update(payload).digest('hex');await db.add(auditTable,[{sequence,action,entityType,entityId,detail,actorId:actor.userId,actorEmail:actor.email||'',createdAt,previousHash,hash}]);if('id' in head&&head.id)await db.update(headTable,[{id:String(head.id),record:{sequence,hash}}]);return{sequence,hash}}
