import { useState } from 'react';
import type { FormEvent } from 'react';
import { api } from '@appdeploy/client';
import { ArrowRight, BriefcaseBusiness, Building2, Check, LockKeyhole, ShieldCheck, UserCheck } from 'lucide-react';
import { BrandLogo } from './Brand';

type User={userId:string;email?:string;name?:string};
type AccountRole={role:'employer'|'talent';status:string;source:string}|null;
type AgencyAccess={role:string;orgName:string;permissions:string[];status:string}|null;
export type AccessState={accountRole:AccountRole;agencyAccess:AgencyAccess;availableWorkspaces:string[];needsRoleChoice:boolean};
export function RoleOnboarding({user,intended,onComplete,onHome}:{user:User;intended?:'employer'|'talent'|null;onComplete:(role:'employer'|'talent')=>void;onHome:()=>void}){const[role,setRole]=useState<'employer'|'talent'|''>(intended||''),[company,setCompany]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();if(!role)return;setBusy(true);setMessage('');try{await api.post('/api/access/claim',{role,companyName:company});onComplete(role)}catch(err){setMessage((err as{message?:string}).message||'Unable to register this workspace.')}finally{setBusy(false)}};return <main className='sb-role-page'><section><button className='sb-logo' onClick={onHome}><BrandLogo/></button><div className='sb-role-copy'><span>SECURE ACCOUNT SETUP</span><h1>Choose the side of SouthBridge you belong to.</h1><p>Authentication proves who you are. This role determines which customer workspace and APIs your account is allowed to use.</p></div><form onSubmit={submit}><button type='button' className={`sb-role-choice ${role==='employer'?'selected':''}`} onClick={()=>setRole('employer')}><Building2/><p><b>I hire finance talent</b><span>Employer Workspace · role briefs, shortlists and hiring decisions</span></p>{role==='employer'&&<Check/>}</button><button type='button' className={`sb-role-choice ${role==='talent'?'selected':''}`} onClick={()=>setRole('talent')}><UserCheck/><p><b>I’m a finance professional</b><span>Talent Workspace · profile, CV, readiness and matched roles</span></p>{role==='talent'&&<Check/>}</button>{role==='employer'&&<label className='sb-role-company'>Company name<input value={company} onChange={e=>setCompany(e.target.value)} required placeholder='Your UK company or accounting firm'/></label>}<div className='sb-role-lock'><LockKeyhole/><span><b>Your customer role is protected.</b> It cannot be switched from Talent to Employer, or Employer to Talent, from the account interface.</span></div>{message&&<div className='sb-error-box'>{message}</div>}<button className='sb-btn sb-btn-primary full' disabled={!role||busy}>{busy?'Registering workspace…':'Continue to my workspace'} <ArrowRight/></button></form><small>Signed in as {user.email||user.name||'authenticated user'}</small></section></main>}
export function WorkspaceChooser({user,access,onOpen,onSignOut,onHome}:{user:User;access:AccessState;onOpen:(v:string)=>void;onSignOut:()=>void;onHome:()=>void}){return <main className='sb-workspace-page'><header><button className='sb-logo' onClick={onHome}><BrandLogo/></button><button className='sb-link' onClick={onSignOut}>Sign out</button></header><section><span>SECURE WORKSPACES</span><h1>Welcome{user.name?`, ${user.name.split(' ')[0]}`:''}.</h1><p>Only workspaces authorised for this account are shown.</p><div className='sb-workspace-grid'>{access.accountRole?.role==='employer'&&<button onClick={()=>onOpen('employerportal')}><Building2/><b>Employer Workspace</b><span>Roles, shortlists and hiring decisions</span><ArrowRight/></button>}{access.accountRole?.role==='talent'&&<button onClick={()=>onOpen('talentportal')}><UserCheck/><b>Talent Workspace</b><span>Profile, opportunities and readiness</span><ArrowRight/></button>}{access.agencyAccess&&<button onClick={()=>onOpen('command')}><ShieldCheck/><b>Agency Command Center</b><span>{access.agencyAccess.role} · {access.agencyAccess.orgName}</span><ArrowRight/></button>}</div></section></main>}
export function AccessDenied({requested,current,onWorkspace,onHome}:{requested:string;current:string;onWorkspace:()=>void;onHome:()=>void}){return <main className='sb-denied'><section><ShieldCheck/><span>ROLE-BASED ACCESS</span><h1>This account cannot open the {requested}.</h1><p>Your registered account role is <b>{current}</b>. SouthBridge keeps employer, talent and agency data separated even when somebody manually changes the page address.</p><button className='sb-btn sb-btn-primary' onClick={onWorkspace}>Open my workspace</button><button className='sb-link' onClick={onHome}>Return to website</button></section></main>}
export function AuthGate({title,text,onSignIn,onHome}:{title:string;text:string;onSignIn:()=>void;onHome:()=>void}){return <main className='sb-denied'><section><BriefcaseBusiness/><span>SOUTHBRIDGE SECURE ACCESS</span><h1>{title}</h1><p>{text}</p><button className='sb-btn sb-btn-primary' onClick={onSignIn}>Sign in securely <ArrowRight/></button><button className='sb-link' onClick={onHome}>Return to website</button></section></main>}
